export default {
    SET_ACCESS_TOKEN : 'setAccessToken',
    SET_SIGNUP_DATA : 'setSignupData',
    CLEAR_AUTH_DATA: 'clearAuthData',
    TOGGLE_LOADER: 'toggleLoader',
    SET_CURRENT_ROUTE: 'setRouteDetails',
    SHOW_SNACKBAR: 'showSnackbar',
    HIDE_SNACKBAR: 'hideSnackbar',
    SET_FOUND_BUSES : 'setFoundBuses',
    SET_SELECTED_BUS: 'setSelectedBus',
    SET_BUS_ROUTE: 'setBusRoute',
    SET_SELECTED_SEATS: 'setSelectedSeats',
    SET_LOCATIONS: 'setLocations',
    SET_PASSENGER_DETAILS: 'setPassengerDetails',
    SET_CONTACT_DETAILS: 'setContactDetails',
    SET_REQUEST: 'setRequest',
    SET_BOOKINGS: 'setBookings',
    SET_SELECTED_BOOKING: 'setSelectedBooking',
    SET_EMAIL: 'setEmail',
    RESET_DATA: 'resetData',
}